<a href="https://colab.research.google.com/github/rosebuddychomp/Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


Introduction to Tensors

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Tensor to python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
#create a random tensor of size (3,3)
random_tensor=torch.rand(1,3,3)
random_tensor

tensor([[[0.0941, 0.6734, 0.4062],
         [0.4845, 0.3086, 0.7075],
         [0.1145, 0.8440, 0.2304]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#create a random tensor with similar shape to a tensor
random_image_tensor=torch.rand(size=(120,120,3)) # height, width, color channels(r,g,b)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([120, 120, 3]), 3)

Zeros and Ones

In [ ]:
#create tensor with all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
#create tensor with all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32